name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          timeout: 60m
          script: |
            set -e

            echo " Starting Deployment..."
            cd /home/ubuntu/example-laravel-repo

            echo " Enabling maintenance mode..."
            (php artisan down) || true

            echo " Pulling latest code from main..."
            git pull origin main

            echo " Installing PHP dependencies "
            composer install --prefer-dist --no-interaction --no-progress

            echo " Clearing old caches..."
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear

            echo "Running frontend build..."
            npm install --legacy-peer-deps
        
            npm install
            echo " Building frontend..."
            npm run build

            echo " Running database migrations..."
            php artisan migrate --force

            echo " Disabling maintenance mode..."
            php artisan up

            echo " Deployment finished successfully!"
            exit 0
