kname: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, bcmath, pdo, pdo_mysql
        tools: composer:v2

    - name: Copy .env file
      run: cp .env.example .env

    - name: Set environment variables in .env
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Generate Laravel APP_KEY
      run: php artisan key:generate

    - name: Add SSH Key from Secret
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Remote Server
      run: |
        ssh -i ~/.ssh/id_rsa -p 22 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/example-laravel-repo
          echo " Pulling latest code from main branch..."
          git pull origin main

          if [ ! -d "vendor" ]; then
            echo " Vendor directory not found. Installing dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader
          else
            echo " Vendor directory exists. Skipping composer install."
          fi

          echo " Running Laravel migrations and optimizations..."
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
        EOF

